# =============================================================================
#  00-ignores.sh — kingtolga aconfmgr ignore rules
#  tracked: samba, sysctl, grub, fstab, cups, ufw, mkinitcpio, pacman, fonts
# =============================================================================
IgnorePath '/.snapshots/*'
IgnorePath '/boot/initramfs-*'
IgnorePath '/boot/initramfs-*-fallback.img'
IgnorePath '/boot/intel-ucode.img'
IgnorePath '/boot/vmlinuz-*'
IgnorePath '/etc/pacman.d/gnupg/S.*'
IgnorePath '/run/*'
IgnorePath '/tmp/*'
IgnorePath '/usr/lib/ghc-*/lib/package.conf.d/*'
IgnorePath '/usr/lib/udev/hwdb.bin'
IgnorePath '/usr/lib/vlc/plugins/plugins.dat'
IgnorePath '/usr/share/doc/*'
IgnorePath '/usr/share/icons/*/icon-theme.cache'
IgnorePath '/usr/share/licenses/spdx/*'
IgnorePath '/usr/share/man/*'
IgnorePath '/usr/share/mime/application/*'
IgnorePath '/usr/share/mime/audio/*'
IgnorePath '/usr/share/mime/image/*'
IgnorePath '/usr/share/mime/text/*'
IgnorePath '/usr/share/mime/video/*'
IgnorePath '/var/cache/*'
IgnorePath '/var/lib/NetworkManager/*.lease'
IgnorePath '/var/lib/NetworkManager/secret_key'
IgnorePath '/var/lib/NetworkManager/seen-bssids'
IgnorePath '/var/lib/NetworkManager/timestamps'
IgnorePath '/var/lib/colord/*'
IgnorePath '/var/lib/flatpak/*'
IgnorePath '/var/lib/fwupd/pki/*'
IgnorePath '/var/lib/lastlog/*'
IgnorePath '/var/lib/libvirt/images/*'
IgnorePath '/var/lib/mysql/*'
IgnorePath '/var/lib/nfs/*'
IgnorePath '/var/lib/pacman/local/*'
IgnorePath '/var/lib/pacman/sync/*'
IgnorePath '/var/lib/passim/*'
IgnorePath '/var/lib/plasmalogin/.cache/*'
IgnorePath '/var/lib/plocate/*'
IgnorePath '/var/lib/samba/private/msg.sock/*'
IgnorePath '/var/lib/samba/private/secrets.tdb'
IgnorePath '/var/lib/swtpm-localca/*'
IgnorePath '/var/lib/systemd/coredump/*'
IgnorePath '/var/lib/systemd/credential.secret'
IgnorePath '/var/lib/systemd/random-seed'
IgnorePath '/var/lib/tpm2-tss/*'
IgnorePath '/var/lib/upower/*'
IgnorePath '/var/lib/urandom/*'
IgnorePath '/var/log/*'
IgnorePath '/var/spool/cups/*'
# tracked: /etc/samba/smb.conf  /etc/sysctl.d/*  /etc/default/grub
#          /etc/fstab  /etc/mkinitcpio.conf  /etc/pacman.conf
#          /etc/ufw/*  /etc/cups/cupsd.conf  /usr/share/fonts/wps-fonts
