# Subscription configuration file for CUPS v2.4.16
# Written by cupsd
NextSubscriptionId 75
<Subscription 73>
Events job-created server-restarted server-started server-stopped
Owner tolga
Recipient dbus://
LeaseDuration 3600
Interval 0
ExpirationTime 1773757679
NextEventId 1
</Subscription>
<Subscription 74>
Events printer-state-changed printer-restarted printer-shutdown printer-stopped printer-added printer-deleted printer-modified job-state-changed job-created job-completed job-stopped job-config-changed job-progress server-restarted server-started server-stopped server-audit
Owner tolga
Recipient dbus://
LeaseDuration 3600
Interval 0
ExpirationTime 1773757680
NextEventId 1
</Subscription>
