[global]
    workgroup              = WORKGROUP
    server string          = CachyOS Samba
    netbios name           = CACHYOS
    server role            = standalone server
    log file               = /var/log/samba/%m.log
    max log size           = 50
    dns proxy              = no
    map to guest           = bad user
    wins support           = yes
    name resolve order     = bcast host wins
    usershare path         = /var/lib/samba/usershares
    usershare max shares   = 100
    usershare allow guests = yes

[CACHYOS_PUBLIC_FOLIO]
    comment        = CachyOS Public Folio
    path           = /home/tolga/CACHYOS_PUBLIC_FOLIO
    browseable     = yes
    writable       = yes
    valid users    = tolga
    create mask    = 0644
    directory mask = 0755
